### ISSUE TITLE
Add API to edit (fixed) parts of RTP header

### ISSUE THREAD

**Issue by sdroege** [ystreet/rtp-types#3]
Could make it some kind of `RtpPacketMut` (better name please) that derefs into the normal `RtpPacket` for reading purposes, and in addition to the fixed headers it could also give mutable access to specific header extension bytes and the CSRC array (so e.g. CSRCs can be changed but not added/removed).

**Comment by ystreet** [comment]
Mostly fixed by https://github.com/ystreet/rtp-types/pull/7.  CSRCs not done yet but can be added when necessary.
