### ISSUE TITLE
Make `RtpPacketBuilder` generic over payload type and allow custom serialization

### ISSUE THREAD

**Issue by sdroege** [ystreet/rtp-types#5]
Somewhat related to https://github.com/ystreet/rtp-types/issues/4

It would be nice if `RtpPacketBuilder` would be generic over the payload type (this can be added in a backwards-compatible way by making it `RtpPacketBuilder<T = &'a [u8]>`), and a custom callback for writing out the data could be provided to `write_into()`.

This way one could provide a custom type for the payload and "collect" chunks as they're written out to avoid copies. Header/padding would still have to be passed to that function as a `&[u8]`, but actual payload could be taken over more cheaply by e.g. using `bytes::Bytes` or a `gst::Memory` and then collecting the packet in multiple chunks that are then sent over the network via `sendmsg()`.

**Comment by ystreet** [comment]
What if, we had a stateful builder for a list of packets (returned through an iterator) that kept track of at least the sequence number and allowed editing each packet's other header values (marker, csrc, timestamp, extension data, etc) while generating a payload with a `FnMut`.  That would allow the reading side to (dynamically) put as many bytes as it wants into the rtp payload.

On the generating side, a trait to write into whatever the user provided would probably be best here.

Maybe something like: https://gist.github.com/ystreet/ad93b54c02885583385e86f2ea6889eb

**Comment by sdroege** [comment]
Having `Box`es in there seems like a bad idea because of the additional heap allocations.

For writing, this doesn't allow e.g. to append a `gst::Memory` as payload and then when writing it out creating a `gst::Buffer` that contains the header in a new `gst::Memory` and the payload just refs the original `gst::Memory` another time.

**Comment by ystreet** [comment]
The idea is to use the same `RtpPacketListBuilder` for multiple packets. e.g. a complete video frame.  If you are only generating a single packet, then the existing approach is fine already.

Can certainly add a separate `push_payload` function and associated generics on the `RtpWriter` trait for the separate header and payload concern.

**Comment by sdroege** [comment]
I'll later have to read your suggestion more carefully then, I think I didn't understand it :)

**Comment by ystreet** [comment]
Updated gist has a version with a `RtpWriter::push_payload()` with a generic lifetime that seems to work.

**Comment by tp-m** [comment]
I don't need any fancy `gst::Buffer` or `gst::Memory` stuff at this point btw, I just want to be able to generate/writeout N bytes into place directly with a closure or whatever without first writing it all into an intermediary buffer and then having the builder copy it over. (e.g. to swizzle some bytes during payloading)

**Comment by ystreet** [comment]
Custom extension/payload data and modifying payload data on the fly should be reasonably possible now with https://github.com/ystreet/rtp-types/pull/10.

More specific use-cases can be discussed in new issues.
